### ISSUE TITLE
Emoji deprecated and broken

### ISSUE THREAD

**Issue by dnjstlr555** [bull29/tfil#17]
I think twitter emoji has version upped.

**Comment by dnjstlr555** [comment]
![neh](https://steamuserimages-a.akamaihd.net/ugc/934938345595035398/C3B89AA3E35BF037D319D7CB05DD6A56B8F486F5/)<br>
![neh](https://steamuserimages-a.akamaihd.net/ugc/934938345595035796/976E93EBF500FDEAC2ED46D69061B9B0994EB71E/)<br>
some images might helpful to explain

**Comment by bull29** [comment]
Fixed!
